### ISSUE TITLE
Update contributing.md to feed openmeeg needs

### ISSUE THREAD

**Issue by massich** [conda-forge/openmeeg-feedstock#1]
https://github.com/conda-forge/openmeeg-feedstock/blob/b72eb032c5ce62b373e4cf4c6862f577d3ebd871/.github/CONTRIBUTING.md#L1-L15

**Comment by jakirkham** [comment]
So this file gets autogenerated by `conda-smithy`. IOW changes here would get replaced when re-rendering.

Given that, what sorts of things are you hoping to see in this document? Could you please share these suggestions on [the `conda-smithy` issue tracker]( https://github.com/conda-forge/conda-smithy/issues )?
