### ISSUE TITLE
Archiving this feedstock?

### ISSUE THREAD

**Issue by hmaarrfk** [conda-forge/openmeeg-feedstock#17]
### Comment:

This feedstock has many outstanding PRs had seems to not have been updated since 2018. It is likely that users cannot even install this correctly anymore.

Is there any opposition to archiving this?

**Comment by agramfort** [comment]
this makes me sad but I don't have anytime to maintain this. Maybe @papadop as some resources to help here?

**Comment by larsoner** [comment]
This feedstock is working again and hopefully will be more maintainable in the future!
