### ISSUE TITLE
try the effect of scikit-build

### ISSUE THREAD

**Issue by massich** [conda-forge/openmeeg-feedstock#2]
https://github.com/scikit-build/scikit-build

**Comment by larsoner** [comment]
I think the first step would probably be to separate the library building from the swig generation, then we can maybe "just" use `pyproject.toml` nowadays after doing a proper build. This feedstock could produce `libopenmeeg` (which supplies the C++ so/dylib/DLL) and `openmeeg` (which would be a SWIG wrapper for it).

These ideas are in https://github.com/openmeeg/openmeeg/issues/449 and need to happen in the OpenMEEG repo first, so I don't think we need to keep an issue open here for them. Once they work there, it should be fairly easy to make a PR to do them here.
