### ISSUE TITLE
aarch64 builds?

### ISSUE THREAD

**Issue by hoechenberger** [conda-forge/openmeeg-feedstock#55]
Hello, there's no aarch64 build available on conda-forge. I'm not sure if no migration has started because of the [ongoing problems with Travis](https://github.com/conda-forge/status/issues/178), or if there's some manual intervention that needs to be done here … would be amazing if anyone could find the time to look into this. 👍

**Comment by larsoner** [comment]
I don't see `openmeeg` listed in https://conda-forge.org/status/migration/aarch64andppc64leaddition, which is weird because it is listed in https://conda-forge.org/status/migration/armosxaddition for example. Any idea how to request addition to the migration?

**Comment by hoechenberger** [comment]
It could be that the migration bot is currently halted because of https://github.com/conda-forge/status/issues/178

@conda-forge/help-ppc64le @conda-forge/help-python  Is there any chance we could get this feedstock built for `aarch64`? What would we need to do?

**Comment by mfansler** [comment]
I'm not sure https://github.com/conda-forge/status/issues/178 is related. None of this packages upstream dependencies are R related, and so far I've only gotten reports on R feedstock jobs being affected. If you know specific non-R feedstocks that are stuck, then please cross-reference them to https://github.com/conda-forge/status/issues/178.

**Comment by mfansler** [comment]
This feedstock has never requested the migration. Add it to: https://github.com/conda-forge/conda-forge-pinning-feedstock/blob/main/recipe/migrations/arch_rebuild.txt in a PR

**Comment by hoechenberger** [comment]
> This feedstock has never requested the migration. Add it to: https://github.com/conda-forge/conda-forge-pinning-feedstock/blob/main/recipe/migrations/arch_rebuild.txt in a PR

Thanks, I will try that!

**Comment by hoechenberger** [comment]
I have opened a PR: https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/5973

**Comment by hoechenberger** [comment]
Closed via #56 

Thanks for your help, @mfansler!
